services:
  # Backend FastAPI service
  - type: web
    name: pdf-ai-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: POSTGRES_DB
        fromDatabase:
          name: pdf-ai-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: pdf-ai-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: pdf-ai-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: pdf-ai-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: pdf-ai-db
          property: port

  # Frontend Streamlit service
  - type: web
    name: pdf-ai-frontend
    env: python
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: cd frontend && streamlit run app.py
    envVars:
      - key: BACKEND_URL
        value: https://pdf-ai-backend.onrender.com

databases:
  - name: pdf-ai-db
    databaseName: pdf_ai_db
    user: pdf_ai_user
    plan: free
